# Podspec Sources
source 'https://github.com/CocoaPods/Specs.git'

# Configuration
inhibit_all_warnings!
use_frameworks!
platform :ios, '10.0'

# Plugins
plugin 'cocoapods-wholemodule'

# Example App Target
target 'Example' do
    pod 'Pocket', :path => '..'

    # Test Target
    target 'ExampleTests' do
        inherit! :search_paths
    end
end
