# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pocket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pocket
#    pod 'web3swift', :git => 'https://github.com/MercuryProtocol/web3.swift.git', :branch => 'master'
#    pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "develop"
    pod 'SwiftyJSON'

  target 'PocketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PocketUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
