# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pocket' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftKeychainWrapper', :git => 'git@github.com:jrendel/SwiftKeychainWrapper.git', :branch => 'develop'

  
  target 'PocketTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
